### ISSUE TITLE
pombot splash page wireframe for slack app store

### ISSUE THREAD

**Issue by tkellen** [bocoup/pombot#35]
We need a single landing/splash page explaining what pombot is and how to install it.

Some examples of existing work:
https://www.heytaco.chat
https://simplepoll.rocks/

Requirements:
- [x] name and tagline
- [x] some screenshots of pombot in action

**Comment by iamjessklein** [comment]
I made a wireframe for the splash page that will live at pombot.bocoup.com 
The area where there's a mobile device on the desktop version will have a demo that I hope to screencast from my phone. Please let me know if this is the right approach. You can leave feedback on the [desktop](https://invis.io/HA7N5Q1MF#/167094350_Pombot-Home) and [mobile](https://invis.io/HA7N5Q1MF#/167094352_Pombot-Mobile) versions in InVision.

![pombot-home](https://cloud.githubusercontent.com/assets/535012/16098011/fa587346-331e-11e6-9b6a-6de04fb78e45.png)


![pombot-mobile](https://cloud.githubusercontent.com/assets/535012/16098033/19575352-331f-11e6-836e-23a074a0357d.png)

**Comment by jennschiffer** [comment]
i left comments and i also think this is great!

**Comment by iamjessklein** [comment]
Here's my first stab at the look and feel (and in [InVision](https://invis.io/HA7N5Q1MF#/167388895_Pombot-Desk)).

![pombot-desk](https://cloud.githubusercontent.com/assets/535012/16130889/408b85fa-33d9-11e6-879d-0008f7ffd6b9.png)

**Comment by tkellen** [comment]
This is awesome!

**Comment by cowboy** [comment]
This is great! Can we also design for the situation where someone has successfully or unsuccessfully added the integration? After the user clicks the "Add to Slack" button, they're redirected to the Slack server (which is out of our control) but after they are done adding the integration, the browser is redirected back to our server, where we 1) actually attempt to add the integration and 2) display a success or error message.

The success message could be as simple as "Integration successful." and the error message could be any number of things, but probably something along the lines of "Unauthorized." or "Access denied."

Either way, this message needs to be displayed somewhere so that the user feels that they have successfully completed the process, or is made aware of any error preventing them from doing so.

Right now, I have this message displaying at the top of the splash page, but it could easily be on its own page.

**Comment by cowboy** [comment]
FWIW, the Hey Taco success page looks like this. We wouldn't need the "activate your account" bit.

![](https://i.gyazo.com/66c8532316065cc04a55426d7a109fa3.png)

**Comment by cowboy** [comment]
Also, see #44. It's separate, but related to this issue.

**Comment by cowboy** [comment]
Do we want to show that people can `/dm @pombot` to start their own personal pom?
